apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-lab.fullname" . }}
  labels:
    {{- include "home-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.auth.jwtSecret | quote }}
  google-client-id: {{ .Values.backend.google.clientId | quote }}
  google-client-secret: {{ .Values.backend.google.clientSecret | quote }}
  gocardless-secret-id: {{ .Values.backend.gocardless.secretId | quote }}
  gocardless-secret-key: {{ .Values.backend.gocardless.secretKey | quote }}
